-- MySQL Script generated by MySQL Workbench
-- 11/18/14 00:38:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema u961758316_uefs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema u961758316_uefs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `u961758316_uefs` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `u961758316_uefs` ;

-- -----------------------------------------------------
-- Table `u961758316_uefs`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u961758316_uefs`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `Senha` VARCHAR(255) NOT NULL,
  `Telefone1` VARCHAR(255) NOT NULL DEFAULT 0,
  `Data_Nascimento` DATE NULL,
  `Sexo` CHAR NOT NULL,
  `Telefone2` VARCHAR(255) NULL DEFAULT 0,
  `Foto` VARCHAR(255) NULL,
  `Strikes` INT NULL DEFAULT 0,
  `Status` INT NULL DEFAULT 0,
  `VotosPositivos` INT NULL DEFAULT 0,
  `VotosNegativos` INT NULL DEFAULT 0,
  `regra` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `Email`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `u961758316_uefs`.`servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u961758316_uefs`.`servicos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `Descricao` TEXT NOT NULL,
  `Preco` DOUBLE NOT NULL,
  `Data_Publicacao` DATE NULL,
  `Data_Vencimento` DATE NULL,
  `Foto_Video` VARCHAR(255) NULL,
  `Bloqueado` INT NULL DEFAULT 0,
  `Expirado` INT NULL DEFAULT 0,
  `ACombinar` INT NULL DEFAULT 0,
  `usuario_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `u961758316_uefs`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u961758316_uefs`.`comentarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Data` DATE NOT NULL,
  `Texto` TEXT NOT NULL,
  `usuario_id` INT NOT NULL,
  `servico_id` INT NULL,
  `produto_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `u961758316_uefs`.`mensagems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u961758316_uefs`.`mensagems` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Assunto` VARCHAR(255) NOT NULL,
  `Texto` TEXT NOT NULL,
  `Data` DATE NULL,
  `Destinatario` VARCHAR(255) NULL,
  `Emisor` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `u961758316_uefs`.`terceiros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u961758316_uefs`.`terceiros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `NomeEmpresa` VARCHAR(255) NOT NULL,
  `Imagem` VARCHAR(255) NULL,
  `ValorPago` DOUBLE NOT NULL,
  `category_id` INT NOT NULL,
  `DataInicio` DATE NOT NULL,
  `link` VARCHAR(255) NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `u961758316_uefs`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u961758316_uefs`.`produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `Descricao` TEXT NOT NULL,
  `Preco` DOUBLE NOT NULL,
  `Data_Publicacao` DATE NULL,
  `Data_Vencimento` DATE NULL,
  `Quantidade` INT NOT NULL DEFAULT 0,
  `Foto_Video` VARCHAR(255) NULL,
  `Bloqueado` INT NULL DEFAULT 0,
  `Expirado` INT NULL DEFAULT 0,
  `CondicaoUso` TEXT NULL,
  `usuario_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `u961758316_uefs`.`reports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u961758316_uefs`.`reports` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Texto` TEXT NOT NULL,
  `Data` DATE NOT NULL,
  `produto_id` INT NULL,
  `servico_id` INT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `u961758316_uefs`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u961758316_uefs`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- --------------------------------------------------------

--
-- Estrutura da tabela `user_bloq`
--

CREATE TABLE IF NOT EXISTS `user_bloq` (
`id` int(11) NOT NULL,
  `Usuario_id` int(11) NOT NULL,
  `dataBloq` date NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

-- --------------------------------------------------------



-- -----------------------------------------------------
-- Table `u961758316_uefs`.`negociacaos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u961758316_uefs`.`negociacaos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NULL,
  `produto_id` INT NULL,
  `servico_id` INT NULL,
  `interessado` INT NULL,
  `data_final` DATE NULL,
  `status` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
