 <h3>CONSIDERAÇÕES INICIAIS</h3>
  <p> <p align=justify> A UEFStore é um provedor de serviço hospedado sob o domínio uefstore.url.ph, de propriedade da SoftComp Empreendimentos Ltda., Avenida Transnordestina s/n, Novo Horizonte, Feira de Santana - BA, CEP 44036-900. </p><br>
  <p> <p align=justify> O serviço oferecido pela UEFStore consiste na oferta aos usuários de internet de uma plataforma de classificados virtuais, sob o contexto da Universidade Estadual de Feira de Santana (UEFS) e arredores. Portanto, atua hospedando gratuitamente conteúdo de terceiros, ou seja, anúncios virtuais postados por seus usuários (“Usuário(s)”). </p><br>
  <p> <p align=justify> Deste modo, o Usuário publica um anúncio no site da UEFStore com todos os detalhes possíveis, o Usuário que se interessar pode entrar em contato com o anunciante, para negociação e conclusão da transação, todos eles ocorridos fora do ambiente do site UEFStore. </p><br>
  <p> <p align=justify> O Usuário que utiliza o site UEFStore para anunciar produtos e/ou serviços, ou ainda encontrar as informações que procura, o faz por sua conta e risco, sem que a UEFStore seja responsável pela veracidade dos dados especificados pelos Usuários, nem pela qualidade e demais detalhes daquilo que é ofertado. A UEFStore não participa, aconselha e/ou interfere, de qualquer forma, da negociação e/ou efetivação de quaisquer transações, apenas disponibiliza dados sobre a reputação dos Usuários, além de não se responsabilizar pela entrega de qualquer produto adquirido. </p><br>

  <h3>1. ACEITE</h3>
<p><p align=justify> 1.1. A UEFStore oferece ao Usuário um conjunto de recursos online (“Serviços”) para o uso da plataforma de classificado virtual regido por estes Termos e Condições de Uso e Acesso da UEFStore (“T&C”).
</p><br>
<p> <p align=justify> 1.2. A utilização dos Serviços implica na total compreensão, aceitação e vinculação automática do Usuário aos T&C. Ao utilizar quaisquer dos Serviços ofertados, o Usuário concorda em respeitar e seguir todas e quaisquer diretrizes dispostas nestes T&C.
</p><br>
<p><p align=justify>1.3. Caso tenha alguma objeção a quaisquer itens, diretrizes ou alterações posteriores destes T&C, ou, ainda, caso fique insatisfeito com os Serviços oferecidos pela UEFStore, por qualquer motivo que seja, o Usuário poderá cessar o uso imediatamente, sem obrigação.
</p><br>
<p><p align=justify>1.4. Estes T&C poderão sofrer alterações periódicas, seja por questões legais ou estratégicas da UEFStore. O Usuário desde já concorda e reconhece que é de sua única e inteira responsabilidade a constante verificação destes T&C.
</p><br>
  <h3>2. POLÍTICA DE USO</h3>
<p><p align=justify>2.1. O Usuário está ciente de que todos os anúncios disponíveis no site são produzidos e disponibilizados por terceiros, sem que haja qualquer tipo de controle, monitoramento ou verificação prévia da UEFStore. A UEFStore não controla, não edita, não monitora e não é, de qualquer forma, responsável pelos anúncios (“Anúncios”) e  mensagens, comentários, publicidade, arquivos, imagens, fotos, vídeos, ou qualquer outro material disponibilizado ou não através dos Anúncios (“Conteúdo”) e submetidos ao site por seus Usuários. O Usuário também concorda que ao utilizar o site poderá se expor a Conteúdo eventualmente ofensivo, inexato, enganoso ou, de qualquer outro modo, censurável.</p><br>
<p><p align=justify>2.1.1. O Usuário concorda que deve avaliar e assumir quaisquer riscos associados a qualquer Conteúdo e/ou Anúncio submetido ao site. Sob nenhuma circunstância, a UEFStore será responsável, de qualquer forma que seja, pelo Conteúdo e/ou pelas perdas ou danos incorridos em função do uso, submissão e acesso de qualquer Conteúdo e/ou Anúncio listado, disponibilizado através do site.</p><br>
<p><p align=justify>2.1.2. Mesmo ciente de que a UEFStore não realiza nenhuma triagem prévia do Conteúdo e não o submete a um processo prévio de aprovação, o Usuário reconhece que a UEFStore terá o direito (mas não a obrigação) de, a seu exclusivo critério, recusar, excluir ou mover qualquer Conteúdo e/ou Anúncio disponibilizado no site, seja por violação aos T&C ou por quaisquer outras razões de ordem ética, legal ou moral.</p><br>
<p><p align=justify>2.2. O Usuário é o único responsável por todo o Anúncio e/ou Conteúdo de sua autoria ou por ele divulgado; assim como pelo seu uso, divulgação ou publicação, devendo o Usuário manter a UEFStore, seus funcionários, parceiros e controladores livres e imunes de toda e qualquer consequência advinda de seus atos/ omissões, inclusive em relação a terceiros.</p><br>
<p><p align=justify>2.2.1. Com relação ao Anúncio e/ou Conteúdo divulgado, transmitido ou associado a link no Site, o Usuário declara que:</p><br>
<p><p align=justify>(i) É o titular dos direitos e/ou possui as autorizações necessárias para divulgar o Conteúdo e permitir que a UEFStore o utilize e/ou ocasionalmente o formate para melhor disposição no Site;</p><br>
<p><p align=justify>(ii) Possui o consentimento expresso, licença e/ou permissão de toda e qualquer pessoa identificável no Conteúdo, seja ela para usar seu nome e/ou sua imagem.</p><br>
<p><p align=justify>2.3. A UEFStore não ratifica, edita, aprova ou monitora previamente qualquer Anúncio, Conteúdo, comentário, opinião ou recomendação expressos no Site e não assume quaisquer responsabilidades a eles relacionadas.</p><br>
<p><p align=justify>2.3.1. A UEFStore não permite, e o Usuário desde já aceita e concorda, a submissão ao Site de Anúncios e/ou Conteúdos de qualquer forma relacionados a atividades que desrespeitem direitos de propriedade intelectual, ou qualquer outra violação a direitos de terceiros, e poderá remover todo o Anúncio e/ou Conteúdo inadequado, quando devidamente notificada de que o mesmo viola direitos de terceiros ou a legislação brasileira.</p><br>
<p><p align=justify>2.3.2. A UEFStore se reserva o direito de remover o Anúncio e/ou qualquer Conteúdo submetido ao Site sem aviso prévio. A UEFSTORE PODERÁ, A SEU EXCLUSIVO CRITÉRIO, SUSPENDER OU CANCELAR O CADASTRO E/OU ACESSO DO USUÁRIO AO SITE EM CASO DE INFRAÇÃO A QUALQUER DAS DISPOSIÇÕES DESTES T&C. A UEFStore também se reserva o direito de decidir, a seu único e exclusivo critério, quais Conteúdos e/ou Anúncios entende como inadequados. Apenas a título exemplificativo, são entendidos como inadequados Anúncios e/ou Conteúdos listados no item 3 e 17 abaixo.</p><br>
  <h3>3. POLÍTICA DE CONTEÚDO E PENALIDADES</h3>
<p><p align=justify>
3.1. A UEFStore não permite, e desde já considera como inadequado, quaisquer Anúncios e/ou Conteúdos enquadrados na lista abaixo. Desta forma, o Usuário compromete-se a não divulgar ou disponibilizar de qualquer outro modo, Conteúdo e/ou Anúncio:</p><br>
<p><p align=justify>(i) Ilícito;</p><br>
<p><p align=justify>(ii) Protegido por direitos autorais, segredo comercial, industrial ou de terceiros; a menos que o Usuário tenha permissão do titular de tais direitos para divulgar o Conteúdo e/ou Anúncio;</p><br>
<p><p align=justify>(iii) Nocivo, abusivo, difamatório, pornográfico, libidinoso ou que de qualquer forma represente assédio, invasão de privacidade ou risco a menores;</p><br>
<p><p align=justify>(iv) Que represente assédio, degradação, intimidação ou ódio em relação a um indivíduo ou grupo de indivíduos com base na religião, sexo, orientação sexual, raça, origem étnica, idade ou deficiência;</p><br>
<p><p align=justify>(v) Que inclua informações pessoais ou que permitam a identificação de terceiro sem seu expresso consentimento;</p><br>
<p><p align=justify>(vi) Falso, fraudulento, enganoso ou que represente venda casada ou promoção enganosa;</p><br>
<p><p align=justify>(vii) Que represente ou contenha marketing de associação ilícito, referência a link, spam, correntes ou esquemas de pirâmide;</p><br>
<p><p align=justify>(viii) Que divulgue, mencione ou faça apologia a quaisquer serviços ilegais ou venda de quaisquer itens cujo comércio e propagandas sejam proibidas ou restritas por lei;</p><br>
<p><p align=justify>(ix) Que contenha vírus ou qualquer outro código malicioso, arquivos ou programas projetados para interromper, destruir ou limitar a funcionalidade de qualquer software ou hardware;</p><br>
<p><p align=justify>(x) Que interrompa o fluxo normal de diálogo com um número excessivo de mensagens, ou que, de outro modo, afete de forma negativa a capacidade de outros Usuários de usar os Serviços; ou</p><br>
<p><p align=justify>(xi) Que utilize endereços de e-mail enganosos, títulos falsos ou, de outro modo, identificadores manipulados para ocultar a origem do Conteúdo e/ou Anúncio submetido ao site.</p><br>
<p><p align=justify>3.1.1. Além disso, o Usuário concorda em não:</p><br>
<p><p align=justify>(i) Perseguir, ou que qualquer de outro modo, assediar terceiros;</p><br>
<p><p align=justify>(ii) Obter, guardar, divulgar, comercializar e/ou utilizar dados pessoais sobre outros Usuários para fins comerciais ou ilícitos;</p><br>
<p><p align=justify>(iii) Usar meios automáticos, incluindo spiders, robôs, crawlers, ferramentas de captação de dados ou similares para baixar dados do site – exceto quando for o caso de ferramentas de busca na Internet (ex. Google Search) e arquivos públicos não comerciais (ex. archive.org);</p><br>
<p><p align=justify>(iv) Divulgar Conteúdo e/ou Anúncio que não seja nacional;</p><br>
<p><p align=justify>(v) Divulgar repetidas vezes (duplicar anúncios) o mesmo Conteúdo e/ou Anúncio ou similar ou ainda impor demanda de tráfego excessiva ou desproporcionalmente grande e que prejudique a infraestrutura do site;</p><br>
<p><p align=justify>(vi) Divulgar o mesmo Anúncio, Conteúdo, item ou serviço em mais de uma categoria; Tentar obter acesso não autorizado aos sistemas da UEFStore ou se envolver em qualquer atividade que interrompa, reduza a qualidade, interfira o desempenho ou prejudique as funcionalidades de qualquer das ferramentas do site; ou</p><br>
<p><p align=justify>(vii) Utilizar quaisquer dispositivos automatizados ou programas de computador que permitam a postagem de Anúncios e/ou Conteúdos no Site sem que cada um deles seja inserido manualmente pelo Usuário (dispositivo automatizado de postagem), inclusive, a título meramente exemplificativo, o uso de tais dispositivos para envio em massa de anúncios, ou o envio de anúncios em intervalos regulares;</p><br>
<p><p align=justify>(viii) Incluir Links/URLs/Endereços eletrônicos de qualquer website que direcionem a qualquer outra página na Internet, seja ela da própria UEFStore, seja um blog, site de fabricantes, página explicativa, ou qualquer outra. Da mesma forma o endereço do e-mail do anunciante só poderá constar no local indicado no momento do cadastro do anúncio, não poderá de forma alguma estar disposto na descrição do anúncio, no título ou nas fotos.</p><br>
<p><p align=justify>(ix) Utilizar quaisquer dispositivos automatizados ou programas de computador (ferramenta de flagging) que permita o uso do sistema de flagging da UEFStore ou de sistemas de moderação de outras comunidades, sem que cada flag seja inserido manualmente (dispositivo automatizado de flagging) ou utilizar a ferramenta de flagging para remover anúncios de concorrentes ou remover anúncios sem acreditar que representem violação a estes Termos e Condições.</p><br>
<p><p align=justify>3.2. A listagem prevista neste item 3 possui caráter meramente exemplificativo e não exaustivo.
</p><br>
  <h3>4. ACESSO AO SITE</h3>
<p> <p align=justify>4.1. A UEFStore concede ao Usuário uma autorização revogável a qualquer momento e sem aviso prévio, não-exclusiva e limitada para acessar o Site e utilizá-lo de modo pessoal. Esta licença não inclui:</p><br>
<p><p align=justify>
(i) Acesso ao Site por agentes de postagem; e</p><br>
<p><p align=justify>(ii) Coleta, cópia, duplicação, divulgação ou uso diverso daquele para o qual foi proposto o Conteúdo em si, bem como o uso de ferramentas de coleta e/ou análise de dados, robôs e mecanismo similares para quaisquer propósitos não autorizados expressamente pela UEFStore.
</p><br>
<p><p align=justify> 4.2. É permitida a criação de hyperlink para a página inicial da UEFStore, desde que o link não denigra, de qualquer forma, a imagem da UEFStore, de seus empregados ou associados ou que apresente conteúdo falso, enganoso, depreciativo ou, ofensivo de qualquer outro modo. </p><br>
<p><p align=justify> 4.3. O uso do Site para além do âmbito de acesso autorizado pela UEFStore implicará na revogação imediata da licença aqui concedida sem prejuízo das penalidades legais. </p><br>
  <h3>5. ANÚNCIOS DESTACADOS (“DESTAQUES”)</h3>
<p><p align=justify> 5.1. A UEFStore oferece aos seus Usuários o serviço denominado Destaques, os Anúncios são exibidos de acordo com as datas de publicações dos mesmos, os últimos Anúncios cadastrados rebem característica de Destaque. </p><br>
  <h3>6. NOTIFICAÇÃO SOBRE INFRAÇÕES</h3>
<p><p align=justify>6.1. Caso qualquer pessoa, Usuário ou não, se sentir lesado em relação a qualquer Anúncio e/ou Conteúdo, poderá encaminhar à UEFStore notificação por escrito solicitando sua retirada.</p><br>
<p><p align=justify>6.2. No entanto, para não prejudicar Usuários de boa-fé, a retirada do Anúncio e/ou Conteúdo do Site pela UEFStore dependerá de efetiva comprovação ou forte evidência da ilegalidade ou infração à lei, direitos de terceiros e/ou aos T&C.</p><br>
<p><p align=justify>6.3. As notificações deverão ainda conter as seguintes informações:
<p><p align=justify>a) Assinatura física ou eletrônica da pessoa supostamente lesada, ou, se for o caso, do titular do direito intelectual violado;</p><br>
<p><p align=justify>b) Identificação do objeto protegido por direitos intelectuais que tenha sido violado se for o caso;</p><br>
<p><p align=justify>c) Identificação do material que supostamente representa a infração, código do(s) Anúncio(s) e/ou link do(s) Anúncio(s), ou, em caso de não se tratarem de Anúncios, informações necessárias para a devida identificação do Conteúdo;</p><br>
<p><p align=justify>d) Declaração de que o notificante possui elementos suficientes para embasar a alegação de violação legal.</p></p><br>
<p><p align=justify>6.4. As notificações deverão ser encaminhadas à UEFStore através do formulário disponível no link "Fale Conosco". Quaisquer outros feedbacks, comentários, sugestões, críticas, solicitações de suporte técnico e outras comunicações também devem ser direcionadas ao atendimento ao cliente da UEFStore clicando no link “Fale Conosco” no site. O notificante reconhece que caso não cumpra com todos os requisitos deste item 4, sua notificação poderá não ser considerada.</p><br>
  <h3>7. POLÍTICA DE PRIVACIDADE E DIVULGAÇÃO DE INFORMAÇÕES</h3>
<p><p align=justify>7.1. O Usuário desde já autoriza a UEFStore a, a seu critério, preservar, armazenar todos os Anúncios e/ou Conteúdos submetidos ao site, bem como todos os seus dados pessoais, a exemplo de endereços de e-mail, endereços de IP (Internet Protocol), informações de data e horário de acesso, entre outras informações. O Usuário também autoriza a UEFStore a informar e/ou divulgar de acordo com a legislação vigente, estes dados em caso de exigência legal ou se razoavelmente necessárias para: cumprir com o devido processo legal; fazer cumprir estes T&C; responder a alegações de suposta violação de direitos de terceiros e de divulgação indevida de informações para contato de terceiros (por exemplo, número de telefone, endereço residencial), e para proteger os direitos, a propriedade ou a segurança de terceiros ou da própria UEFStore e de seus Usuários.</p><br>
<p><p align=justify>7.2. A utilização do Site implica no consentimento do Usuário para coleta, armazenamento e uso das informações pessoais fornecidas e suas atualizações, dados de tráfego, endereços IP, entre outros.</p><br>
<p><p align=justify>7.3. O Site poderá, eventualmente, conter links para sites de terceiros. A UEFStore não se responsabiliza pelo conteúdo ou pela segurança das informações do Usuário quando acessar sites de terceiros. Tais sites podem possuir suas próprias políticas de privacidade quanto ao armazenamento e conservação de informações pessoais, completamente alheias à UEFStore.</p><br>
<p><p align=justify>7.4. Ao publicar um anúncio na UEFStore, o Usuário compreende que os anúncios e o Conteúdo são públicos e acessíveis a terceiros, podendo ser listados nos resultados de ferramentas de pesquisa como Yahoo!, MSN, Google e outros e no cache dessas ferramentas de pesquisa.</p><br>
<p><p align=justify>7.5. A UEFStore poderá utilizar as informações e/ou dados fornecidos e/ou coletados pelo usuário para:</p><br>
<p><p align=justify>(i) Aplicar estes T&C;</p><br>
<p><p align=justify>(ii) Acompanhar as atividades do Usuário, utilizando palavras chave de pesquisas e novos anúncios para administrar mais efetivamente o tráfego no Site;</p>
<p><p align=justify>(iii) Prestar serviços ao Usuário;</p><br>
<p><p align=justify>(iv) Criar e administrar Contas de Usuário; e</p><br>
<p><p align=justify>(v) Prestar assistência técnica.</p><br>
<p><p align=justify>7.6. É reservado à UEFStore o direito de bloquear o acesso ao Site de Usuários alocados em alguns países.</p><br>
<p><p align=justify>7.7. As informações e dados cadastrais do Usuário podem ser protegidas por senha e nome de Usuário exclusivos, pessoais e intransferíveis, que não devem ser divulgadas, quer pela UEFStore, quer pelo próprio Usuário.</p><br>
<p><p align=justify>7.8. O Usuário desde já declara estar ciente que a UEFStore não assume nenhuma responsabilidade em caso de roubo, perda, alteração ou uso indevido de suas informações pessoais e do Conteúdo como um todo, inclusive na hipótese de informações fornecidas a prestadores de serviços terceirizados ou a outros Usuários e na hipótese de descumprimento destes T&C por prestadores de serviços terceirizados.</p><br>
<p><p align=justify>7.9. O Usuário precisa se cadastrar para postar ou responder a Anúncios no Site. Ao efetuar cadastro no site da UEFStore para postar ou responder anúncios, o Usuário manifesta aceite aos Termos e Condições de Uso da UEFStore.
</p><br>
  <h3>8. DIREITOS DE PROPRIEDADE INTELECTUAL</h3>
<p><p align=justify> 8.1. Os elementos e/ou ferramentas encontrados no site, com exceção dos Conteúdos e/ou Anúncios submetidos por Usuários são de titularidade ou licenciados pela UEFStore, sujeitos aos direitos intelectuais de acordo com as leis brasileiras e tratados e convenções internacionais dos quais o Brasil seja signatário. Apenas a título exemplificativo, entendem-se como tais: textos, softwares, scripts, imagens gráficas, fotos, sons, músicas, vídeos, recursos interativos e similares, marcas, marcas de serviços, logotipos. </p><br>
<p><p align=justify> 8.2. Os elementos e/ou ferramentas que são disponibilizados para o Usuário no site os são tão e somente no ESTADO EM QUE SE ENCONTRAM e apenas para sua informação e uso pessoal na forma designada pela UEFStore. Tais elementos e/ou ferramentas não podem ser usados, copiados, reproduzidos, distribuídos, transmitidos, difundidos, exibidos, vendidos, licenciados ou, de outro modo, explorados para quaisquer fins, sem o consentimento prévio e por escrito da UEFStore. </p><br>
<p><p align=justify> 8.3. A UEFStore reserva a si todos os direitos que não foram expressamente previstos em relação ao Site, aos seus elementos e/ou ferramentas. O usuário compromete-se a não usar, reproduzir ou distribuir quaisquer elementos e/ou ferramentas que não sejam expressamente permitidos pela UEFStore – inclusive o uso, reprodução ou distribuição para fins comerciais dos Anúncios e/ou Conteúdos extraídos do site. Caso o Usuário faça qualquer cópia, seja ela via download ou impressão, dos elementos e/ou ferramentas da UEFStore para uso exclusivamente pessoal, deverá preservar todos os direitos de propriedade intelectual inerentes. O Usuário concorda em não burlar, desativar ou, de alguma forma, interferir em recursos e/ou ferramentas relacionados à segurança do site, sob pena de incorrer nas medidas judiciais cabíveis. </p><br>

  <h3>9. GARANTIA DE ANÚNCIO E/OU CONTEÚDO</h3>
<p><p align=justify> 9.1. O Usuário está ciente de que, ao acessar o Site da UEFStore, (i) estará exposto a Anúncios e/ou Conteúdos de uma variedade de fontes não validadas ou garantidas previamente pela UEFStore, e (ii) que a UEFStore não é responsável pela sua precisão, veracidade, legalidade, licitude, utilidade e/ou segurança destes Anúncios e/ou Conteúdos. </p><br>
<p><p align=justify> 9.2. A UEFStore também não garante o sucesso nas transações ou informações buscadas no site. </p><br>
  <h3>10. LIMITAÇÃO DE RESPONSABILIDADE</h3>
<p><p align=justify> O Usuário se compromete a defender, indenizar e isentar de qualquer responsabilidade a UEFStore com relação a toda e qualquer reclamação, perda, dano, obrigação, custos, dívidas ou despesas (incluindo, entre outros, honorários advocatícios e custas processuais) incorridas em razão de: (i) mau uso e acesso do Site da UEFStore; (ii) violação e/ou não observância de quaisquer dispositivos destes T&C; (iii) violação de qualquer direito de terceiros, incluindo, mas sem se limitar a, qualquer direito proprietário ou de privacidade; ou (iv) qualquer reclamação de que algum Anúncio e/ou Conteúdo causou dano a terceiros. Esta defesa e obrigação de indenização subsistirão a estes T&C e ao uso e/ou acesso do site. </p><br>

  <h3>11. TRANSAÇÕES ENTRE USUÁRIOS</h3>
<p><p align=justify> 11.1. A UEFStore não será responsável pelos negócios e/ou transações, efetivadas ou não, entre Usuários. Apenas a título exemplificativo, entendem-se como tais negócios: o pagamento e entrega de bens e serviços e quaisquer outros termos, condições, garantias ou representações associadas a essas transações. Tais transações são realizadas entre Usuários, e portanto de sua exclusiva responsabilidade, sem qualquer envolvimento ou participação da UEFStore. </p><br>
<p><p align=justify> 11.2. O usuário está ciente de que a UEFStore não deve ser responsabilizada ou sujeitar-se a quaisquer perdas e/ou danos incorridos em face destas transações. Os usuários concordam que, em caso de litígio entre Usuários, a UEFStore não será, de qualquer forma, envolvida ou responsabilizada. </p><br>
  <h3>12. LIMITAÇÃO E TÉRMINO DO SERVIÇO</h3>
<p><p align=justify> 12.1. O Usuário reconhece que a UEFStore pode estabelecer limites referentes ao uso e acesso do site, inclusive quanto ao número máximo de dias que um anúncio será exibido no site, o número e tamanho máximo de textos, mensagens de e-mail ou outros Anúncios e/ou Conteúdos que possam ser transmitidos ou armazenados no site. </p><br>
<p><p align=justify> 12.2. O anúncio aparecerá por 30 dias de sua publicação nas ferramentas de busca do site, após este prazo, ele não será mais exibido nos resultados da ferramenta de “busca”, entretanto, poderá ser renovado pelo Usuário responsável. O anúncio também deixará de aparecer nas ferramentas “Meus Produtos”, no caso de produto, e “Meus Serviços”, no caso de serviço. </p><br>
<p><p align=justify> 12.3. O usuário concorda que a UEFStore, a seu critério, pode excluir ou desativar sua conta, bloqueá-la, ou, de outro modo, encerrar seu acesso ou uso do Site (ou parte dele) imediatamente, sem aviso prévio, além de remover qualquer Anúncio e/ou Conteúdo do site. </p><br>
  <h3>13. TRANSFERÊNCIA DE DIREITOS</h3>
<p><p align=justify> 13.1. Estes T&C, bem como quaisquer direitos, licenças e/ou autorizações implícitas ou expressas concedidas pela UEFStore aos seus Usuários, não podem ser cedidos, ou de qualquer forma transferidos, pelo Usuário. </p><br>

  <h3>14. CAPACIDADE DO USUÁRIO EM USAR OS SERVIÇOS OFERECIDOS PELO SITE</h3>
<p><p align=justify> 14.1. O Usuário, se pessoa física, declara ser maior de 18 anos, menor emancipado, ou possuir o consentimento legal, expresso e por escrito, dos pais ou responsável legal e ser plenamente capaz para se vincular a estes T&C, acatar e cumprir com suas disposições. </p><br>
<p><p align=justify> 14.2. Menores de idade não devem enviar informações pessoais, tais como endereço de e-mail, nome e/ou informação para contato à UEFStore. Apenas os pais ou responsáveis legais estão autorizados a entrar em contato com a UEFStore. </p><br>
<p><p align=justify> 14.3. O Usuário, sendo pessoa jurídica, o fará na figura do seu representante legal, respeitando as mesmas disposições do item 13.1 acima. </p><br>
  <h3>15. REGRAS GERAIS, LEGISLAÇÃO APLICÁVEL</h3>
<p><p align=justify> 15.1. Estes T&C e quaisquer outras políticas divulgadas pela UEFStore no Site estabelecem o pleno e completo acordo e entendimento entre o Usuário superando e revogando todos e quaisquer entendimentos, propostas, acordos, negociações e discussões havidos anteriormente entre as partes.</p><br>
<p><p align=justify> 
15.2. Os T&C e a relação entre as partes são regidos pelas leis da República Federativa do Brasil. </p><br>
<p><p align=justify> 15.3. A incapacidade da UEFStore em exercer ou fazer cumprir qualquer direito ou cláusula dos T&C não representa uma renúncia desse direito ou cláusula. </p><br>
<p><p align=justify> 15.4. Na hipótese de que qualquer item, termo ou disposição destes T&C vir a ser declarado nulo ou não aplicável, tal nulidade ou inexequibilidade não afetará quaisquer outros itens, termos ou disposições aqui contidos, os quais permanecerão em pleno vigor e efeito. </p><br>
  <h3>16. PRODUTOS E SERVIÇOS NÃO PERMITIDOS NA UEFStore:</h3>
<p><p align=justify>Somente poderão ser veiculados na UEFStore anúncios de produtos e/ou serviços permitidos pelos Termos de Uso da UEFStore e pela lei vigente. Os anunciantes são responsáveis pelos produtos e serviços oferecidos e devem certificar-se da autenticidade e legalidade de seus anúncios. A UEFStore poderá cancelar anúncios que infrinjam os Termos de Uso de sua plataforma ou a Lei Vigente.</p><br>
<p><p align=justify>O anunciante tem plena ciência de que seus dados de cadastro e/ou dados de acesso serão informados se solicitados por autoridades competentes, em conformidade com a legislação vigente.</p><br>
<p><p align=justify>Ao cadastrar um anúncio o usuário deve verificar a listagem de produtos proibidos na UEFStore:</p><br>
<p><p align=justify>16.1. Qualquer tipo de serviço e produto ilegal</p><br>
<p><p align=justify>16.2. Serviços ou instruções para importação de bens que resultem em evasão fiscal</p><br>
<p><p align=justify>16.3. Produtos embargados ou com restrição documentária e/ou de qualquer espécie quanto ao seu uso, exploração ou transferência de titularidade e/ou posse.</p><br>
<p><p align=justify>16.4. Propriedade roubada ou furtada.</p><br>
<p><p align=justify>16.5. Cartões de Crédito ou débito, como também, produtos para captura, memória e operacionalização de transações com cartões de crédito.</p><br>
<p><p align=justify>16.6. Noteiros.</p><br>
<p><p align=justify>16.7. Bilhetes de loteria, bilhetes de aposta para corridas de cavalos, raspadinha, rifas, jogos de bingo, máquinas caça-níqueis, jogos de azar.</p><br>
<p><p align=justify>16.8. Anúncios de tarô, horóscopo e/ou qualquer outro serviço de cunho esotérico ou mesmo religioso, como também, mas não exclusivamente, simpatias, correntes, macumba, mandingas, dentre outros.</p>
<p><p align=justify>16.9. Ações, outros títulos e produtos financeiros..</p><br>
<p><p align=justify>16.10. Pessoas, cadáveres, membros e órgãos, sangue, fluídos do corpo, barriga de aluguel.</p><br>
<p><p align=justify>16.11. Documentos de identidade, registros de finanças pessoais e informações pessoais (em qualquer forma, incluindo listas de correspondência), como também, instrumentos que permitam a fabricação ilegal de documentos oficiais.</p><br>
<p><p align=justify>16.12. Uniformes, identidades, equipamentos táticos de uso profissional: polícia e forças armadas.</p><br>
<p><p align=justify>16.13. Armas e itens relacionados (tais como armas de fogo, peças de armas de fogo, revistas, munição, projéteis utilizados em armas de ar comprimido, armas de práticas esportivas, armas de brinquedo que possam ser confundidas com armas verdadeiras, gás lacrimogênio ou qualquer outro gás, aparelhos de choque).</p><br>
<p><p align=justify>16.14. Drogas, narcóticos, tóxicos, substâncias alucinógenas, bem como, equipamentos ou qualquer substância destinada à elaboração ou uso de drogas.</p><br>
<p><p align=justify>16.15. Produtos à base de tabaco ou que estimulem o vício ao tabaco.</p><br>
<p><p align=justify>16.16. Medicamentos, seringas, agulhas e congêneres, equipamentos hospitalares, produtos com atribuições terapêuticas ou fitoterápicas, suplementos, anabolizantes e/ou esteroides.</p><br>
<p><p align=justify>16.17. Aparelhos de ginástica passiva, eletroestimuladores e estéticos.</p><br>
<p><p align=justify>16.18. Cosméticos usados.</p><br>
<p><p align=justify>16.19. Produtos sem a homologação, aprovação e registro de órgãos governamentais como, por exemplo, ANVISA, INMETRO, ANATEL.</p><br>
<p><p align=justify>16.20. Materiais perigosos: cádmio, mercúrio, ácidos - em especial sulfúrico e químicos corrosivos.</p><br>
<p><p align=justify>16.21. Qualquer tipo de veneno, inclusive, pesticidas, inseticidas, raticidas.</p><br>
<p><p align=justify>16.22. Fogos de artifício, pólvora, dispositivos de destruição, material explosivo, botijões de gás, kit gás GNV.</p><br>
<p><p align=justify>16.23. Animais Silvestres ou em extinção, protegidos por lei - IBAMA. Peles de animais em extinção e/ou de caça proibida, como também, animais para rinha.</p><br>
<p><p align=justify>16.24. Produtos que violem leis sobre direito de autor, patente, marcas, modelos, desenhos industriais ou segredos industriais. Ficam desde já expressamente, mas não unicamente, proibidos:</p><br>
<p><p align=justify>16.24.1. Cópias não autorizadas de programas de televisão, campeonatos esportivos, discos, filmes, eventos musicais, seriados, softwares, apostilas de cursos.</p><br>
<p><p align=justify>16.24.2. Réplicas e Falsificações.</p><br>
<p><p align=justify>16.25. Produtos anunciados em sistema de “lotes”/“atacado”, exceção a produtos anunciados diretamente pelo fabricante, como, por exemplo, lotes de roupas de fabricação/confecção própria.</p><br>
<p><p align=justify>16.26. Réplicas, produtos falsificados, adulterados, contrabandeados ou fruto de descaminho.</p><br>
<p><p align=justify>16.27. Cédulas e moedas falsificadas.</p><br>
<p><p align=justify>16.28. Produtos que infrinjam as Leis de Proteção do Patrimônio Histórico, Artístico e Cultural, em especial, antiguidades dos anos de 1500 até 1980 do Brasil e Portugal, como também e não exclusivamente, itens pertencentes ao patrimônio histórico cultural ferroviário brasileiro, como por exemplo, a Rede Ferroviária Nacional - RFFSA, Fepasa, Sorocabana, Mogiana, Vias Férreas, entre outras.</p><br>
<p><p align=justify>16.29. Qualquer material ou programa que se destine a atividade ou a divulgação de práticas de hacking ou cracking (envio de vírus).</p><br>
<p><p align=justify>16.30. Produtos ou serviços que incitem a violência e discriminação seja por orientação sexual, opção religiosa, raça e/ou nacionalidade.</p><br>
<p><p align=justify>16.31. Produtos pornográficos de qualquer natureza, incluindo, mas não unicamente, produtos de sex shop, revistas com conteúdo sexual, vídeos, massagens eróticas, tântricas ou qualquer material ou serviço ofensivo à moral e bons costumes.</p><br>
<p><p align=justify>16.32. Pedofilia, ou qualquer material que faça referência ou envolva menores de idade e pornografia infantil.</p><br>
<p><p align=justify>16.33. Serviços de prostituição e/ou similares</p><br>
<p><p align=justify>16.34. Vídeos amadores, caseiros, câmeras ocultas e/ou qualquer material em que não haja consentimento expresso e inequívoco dos envolvidos.</p><br>
<p><p align=justify>16.35. Qualquer material que abrigue imagens de sexo forçado.</p><br>
<p><p align=justify>16.36. Anúncios de esquemas de franquia, pirâmide, “afiliação de clube”, marketing multinível, organização de distribuição ou representantes de vendas, ou outra oportunidade de negócios similares, como também, oportunidades de negócios que exija o adiantamento de pagamento periódico, exija recrutamento de outros membros, sub-distribuidores ou sub-agentes, ou somente pague comissão.</p><br>